import { Nunito, Source_Code_Pro } from "next/font/google";
import localFont from "next/font/local";
import { clsx } from "clsx";
import "./styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const sans = Nunito({
  weight: ["400", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = Source_Code_Pro({
  weight: ["400", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

const serif = localFont({
  src: [
    {
      path: "./fonts/pp-editorial-new/PPEditorialNew-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/pp-editorial-new/PPEditorialNew-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-serif",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(sans.variable, serif.variable, "font-sans")}>
        {children}
      </body>
    </html>
  );
}
