import { Kalam } from "next/font/google";
import localFont from "next/font/local";
import { clsx } from "clsx";
import "./styles.css";
import { AuthProvider } from "./svg-paths/provider";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const handwriting = Kalam({
  weight: ["400"],
  variable: "--font-handwriting",
  subsets: ["latin"],
});

const sans = localFont({
  src: [
    {
      path: "./fonts/sans/regular.woff2",
      weight: "400",
      style: 'normal',
    },
    {
      path: "./fonts/sans/regular-italic.woff2",
      weight: "400",
      style: 'italic'
    },
    {
      path: "./fonts/sans/bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/sans/bold-italic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/sans/medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/sans/medium-italic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/sans/semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/sans/semibold-italic.woff2",
      weight: "600",
      style: "italic",
    },
    
  ],
  variable: "--font-sans",
});

const mono = localFont({
  src: [
    {
      path: "./fonts/intelone-mono/regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-mono",
});

const serif = localFont({
  src: [
    {
      path: "./fonts/pp-editorial-new/regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/pp-editorial-new/bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-serif",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        /* style={
          {
            "--font-sans": "Basier Circle, system-ui, sans-serif",
          } as CSSProperties
        } */
        className={clsx(
          handwriting.variable,
          serif.variable,
          sans.variable,
          "font-sans antialiased bg-gray4"
        )}
      >
        <AuthProvider>{children}</AuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
